CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL ,
    name VARCHAR(255) NOT NULL ,
    avatar_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()  ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)