CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY ,
    email VARCHAR(255) UNIQUE NOT NULL ,
    name VARCHAR(255) NOT NULL ,
    avatar_url TEXT,
    created_at TIMESTAMPTZ NOT NULL ,
    updated_at TIMESTAMPTZ NOT NULL
)