name: Go CI, Build, Scan and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    name: Test and Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          args: --timeout=5m

  lint-dockerfile:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile

  scan-image-for-pr:
    name: Build and Scan Image for PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build image locally
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          push: false
          tags: local-image-for-pr:latest

      - name: Run Trivy vulnerability scanner on local image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'local-image-for-pr:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  build-and-push-image:
    name: Build and Push Docker Image
    needs: [test, lint-dockerfile]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

  scan-pushed-image:
    name: Scan Pushed Docker Image
    needs: [build-and-push-image]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'ghcr.io/${{ github.repository }}:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'